version: '3.8'
services:
  paytm:
    image: yaswanth111/paytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  movies:
    image: yaswanth111/paytmmovies:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  train:
    image: yaswanth111/paytmtrain:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: yaswanth111/paytmdth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
  recharge:
    image: yaswanth111/paytmrecharge:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
